### ISSUE TITLE
It's just not working

### ISSUE THREAD

**Issue by jamesprakashjc** [grantwilk/DNOISE#41]
It's just not working. Even with Quick D-noise, only 1 or 2 fireflies disappear. The output is almost the same as the raw render. It used to work before though. I don't get it, :/

**Comment by fooditron** [comment]
I tried a large image, and D-Noise button does nothing. With a smaller image, it's throwing an error:

Traceback (most recent call last):
  File "C:\Users\fh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\DNOISE\__init__.py", line 225, in execute
    runpostimgdenoiser()
  File "C:\Users\fh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\DNOISE\__init__.py", line 82, in runpostimgdenoiser
    fmutils.save(SCRIPT_DIR, source_name, DENOISE_SOURCE)
  File "C:\Users\fh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\DNOISE\fmutils.py", line 36, in save
    shutil.copyfile(image.filepath, os.path.join(directory, filename))
  File "D:\Downloads\_APPS\Blender\blender-2.80.0-git.860a9f979d60-windows64\2.80\python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '//..\\Renders\\prison_test_01.png'

location: <unknown location>:-1
